[package]
name = "advent-of-code-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
dotenv = "0.15.0"
reqwest = { version = "0.12", features = ["json", "blocking"] }
